# Matrices, their Null Spaces and Regular Markov Chains
#### Bharath Variar, 2019B5A70930H

## Importing Libraries

In [1]:
import numpy as np
import sympy as sp

## Powers of a Matrix

### Defining functions

In [2]:
def matrix_multiply(matA, matB):
    """
    Returns the product of 2 matrics
    i/p: The two matrices to be multipled matA(n1 x n2), matB(n3 x n4)
    o/p: If n2 == n4: returns n1 x n4 product matrix
         else: returns -1
    """
    if matA.shape[1] != matB.shape[0]:
        print("Matrix multiplication invalid")
        return -1
    else:
        result_mat = np.zeros((matA.shape[0], matB.shape[1]))
        for i in range(matA.shape[0]):  # matA.shape[0] = number of rows
            row = matA[i]
            for j in range(matB.shape[1]):  # matB.shape[1] = number of columns
                col = matB[:, j]
                dot = 0
                for k in range(len(row)):
                    dot += row[k] * col[k]
                result_mat[i][j] = dot
        return result_mat

In [3]:
def matrix_power(matA, power):
    """
    Returns the input matrix raised to the power 'power'
    i/p: Matrix matA(n1 x n2), and integer power
    o/p: If n1 == n2 and power is an integer: Returns matA^power
         else: returns -1
    """
    if type(power) is not int:
        print("Power is not a valid integer")
        return -1
    result_mat = matA
    for i in range(power - 1):
        result_mat = matrix_multiply(result_mat, matA)
        if type(result_mat) is int:
            return -1
    return result_mat

### Implementation

In [4]:
A = np.random.randint(10, size=(3, 3))
print(f"matA:\n {A}")
B = np.random.randint(10, size=(3, 5))
print(f"matB:\n {B}")

matA:
 [[0 3 7]
 [4 3 4]
 [5 6 0]]
matB:
 [[6 3 5 4 4]
 [4 7 2 5 9]
 [4 0 8 5 1]]


In [5]:
print(f'matA x matB: \n{matrix_multiply(A, B)}')

matA x matB: 
[[40. 21. 62. 50. 34.]
 [52. 33. 58. 51. 47.]
 [54. 57. 37. 50. 74.]]


In [6]:
print(f"(matA)^3: \n{matrix_power(A, 3)}")

(matA)^3: 
[[264. 366. 533.]
 [380. 471. 404.]
 [427. 525. 300.]]


## Regular Markov Chain as a Matrix

### Creating Stochastic Matrices

In [7]:
def create_stochastic_matrix(size):
    mat = np.zeros((size, size))
    for i in range(size):
        row_sum = 0
        for j in range(size - 1):
            mat[i][j] = np.random.uniform(0, (1 - row_sum))
            row_sum += mat[i][j]
        mat[i][-1] = 1 - row_sum
    return mat

### Checking Regular Matrix

In [8]:
def check_regular_matrix(matA, iterations= 1000):
    for i in range (1, iterations + 1):
        mat = matrix_power(matA, i)
        if (type(mat) == int): return -1 # matrix_power() returns -1 if error
        mat_size = len(mat) # Matrix has to be a square
        count = 0
        for j in range(mat_size):
            for k in range(mat_size):
                if (mat[j][k] == 0): 
                    break
                else: 
                    count += 1
        if (count == (mat_size ** 2)): 
            print(f"The matrix is regular, and when it is raised to power {i}, it is positive.")
            break
        else:
            print(f"The matrix is not regular upto its {i}th power", end = '\r')
    return

### Implementation

In [9]:
# Debugging for validity of stochastic matrix
# Generate two random stochastic matrices
for i in range(2):
    b = create_stochastic_matrix(4)
    for i in range(4):
        for j in range(4):
            if (b[i][j] < 0 or b[i][j] > 1):
                print("Not Valid Stochastic Matrix")    
    print(b)
    print()

[[0.92996048 0.01553124 0.00520867 0.04929961]
 [0.03771373 0.56865239 0.11991142 0.27372245]
 [0.26385328 0.50121626 0.14137345 0.09355702]
 [0.90311098 0.03987813 0.05080718 0.0062037 ]]

[[0.00467769 0.62530648 0.09168386 0.27833196]
 [0.43588012 0.55835611 0.00097355 0.00479022]
 [0.35907912 0.63551457 0.00451652 0.00088979]
 [0.76078916 0.08616715 0.08173247 0.07131122]]



In [10]:
check_regular_matrix(b)
D = np.array([[0.12351425, 0.50276079, 0.10840787, 0.26531709],
                 [0.8681274, 0., 0.11212622, 0.01974638],
                 [0.55888506, 0.14277434, 0.15657036, 0.14177024],
                 [0.11016633, 0.07586725, 0.40404501, 0.40992142]])
print(f'MatD: \n{D}')
check_regular_matrix(D)
E = np.array([0, 0.5, 0.5, 9.5, 0, 0.5, 0, 1, 0]).reshape(3, -1)
check_regular_matrix(E)

The matrix is regular, and when it is raised to power 1, it is positive.
MatD: 
[[0.12351425 0.50276079 0.10840787 0.26531709]
 [0.8681274  0.         0.11212622 0.01974638]
 [0.55888506 0.14277434 0.15657036 0.14177024]
 [0.11016633 0.07586725 0.40404501 0.40992142]]
The matrix is regular, and when it is raised to power 2, it is positive.
The matrix is regular, and when it is raised to power 4, it is positive.


In [11]:
F = np.array([[0.7, 0, 0.3], [0, 1, 0], [0.2, 0, 0.8]]).reshape(3, -1)
print(f"MatC: \n{F}")
check_regular_matrix(F, 1000)

MatC: 
[[0.7 0.  0.3]
 [0.  1.  0. ]
 [0.2 0.  0.8]]


## Null Space of a Matrix
The null space of a matrix A is the same as the null space for its row reduced echelon form (rref(A)).

In [12]:
def rref(matA):
    rref = matA.copy()
    pivot = 0
    rows = len(rref)
    cols = len(rref[0])
    rank = 0
    for r in range(rows):
        if (cols < pivot):
            break
        i = r
        while (rref[i, pivot] == 0):
            i += 1
            if (rows == 1):
                i = r
                pivot += 1
                if (cols == pivot):
                    break
        vec = rref[i]
        rref[i] = rref[r]
        rref[r] = vec
        if (rref[r][pivot] != 0):
            rref[r] = rref[r] / rref[r][pivot]
        for i in range(rows):
            if (i != r):
                rref[i] -= (rref[r]*rref[i][pivot]) 
        pivot += 1
    for row in range(rows):
        for col in range(cols):
            if (rref[row][col] != 0):
                rank += 1
                break
                
    return rref, rank

In [13]:
G = np.array([1, 2, -1, -4, 2, 3, -1, -11, -2, 0, -3, 22]).reshape(3, -1)
print(f'matF: \n{G}')
rref_g, r = rref(G)
print(f"rref(E): \n{rref_g}")
G = sp.Matrix(G)
print (f"sympy.rref(): \n{np.array(G.rref()[0])}")

matF: 
[[  1   2  -1  -4]
 [  2   3  -1 -11]
 [ -2   0  -3  22]]
rref(E): 
[[ 1  0  0 -8]
 [ 0  1  0  1]
 [ 0  0  1 -2]]
sympy.rref(): 
[[1 0 0 -8]
 [0 1 0 1]
 [0 0 1 -2]]


In [14]:
H = np.array([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]).reshape(3, -1)
print(f"matH:\n{H}")
H = sp.Matrix(H)
null_space = [np.array(mat) for mat in H.nullspace()]
print("H.nullspace(): ")
null_space = [print(f'{mat}') for mat in null_space]

matH:
[[ 1  0  1  3]
 [ 2  3  4  7]
 [-1 -3 -3 -4]]
H.nullspace(): 
[[-1]
 [-2/3]
 [1]
 [0]]
[[-3]
 [-1/3]
 [0]
 [1]]
