# Matrices, their Null Spaces and Regular Markov Chains
#### Bharath Variar, 2019B5A70930H

## Importing Libraries

In [1]:
import numpy as np
import sympy as sp

## Powers of a Matrix

### Defining functions

In [2]:
def matrix_multiply(matA, matB):
    """
    Returns the product of 2 matrics
    i/p: The two matrices to be multipled matA(n1 x n2), matB(n3 x n4)
    o/p: If n2 == n4: returns n1 x n4 product matrix
         else: returns -1
    """
    if matA.shape[1] != matB.shape[0]:
        print("Matrix multiplication invalid")
        return -1
    else:
        result_mat = np.zeros((matA.shape[0], matB.shape[1]))
        for i in range(matA.shape[0]):  # matA.shape[0] = number of rows
            row = matA[i]
            for j in range(matB.shape[1]):  # matB.shape[1] = number of columns
                col = matB[:, j]
                dot = 0
                for k in range(len(row)):
                    dot += row[k] * col[k]
                result_mat[i][j] = dot
        return result_mat

In [3]:
def matrix_power(matA, power):
    """
    Returns the input matrix raised to the power 'power'
    i/p: Matrix matA(n1 x n2), and integer power
    o/p: If n1 == n2 and power is an integer: Returns matA^power
         else: returns -1
    """
    if type(power) is not int:
        print("Power is not a valid integer")
        return -1
    result_mat = matA
    for i in range(power - 1):
        result_mat = matrix_multiply(result_mat, matA)
        if type(result_mat) is int:
            return -1
    return result_mat

### Implementation

In [4]:
A = np.random.randint(10, size=(3, 3))
print(f"matA:\n {A}")
B = np.random.randint(10, size=(3, 5))
print(f"matB:\n {B}")

matA:
 [[3 3 8]
 [4 5 8]
 [0 9 4]]
matB:
 [[7 7 2 1 5]
 [5 6 5 8 5]
 [7 9 7 5 1]]


In [5]:
print(f'matA x matB: \n{matrix_multiply(A, B)}')

matA x matB: 
[[ 92. 111.  77.  67.  38.]
 [109. 130.  89.  84.  53.]
 [ 73.  90.  73.  92.  49.]]


In [6]:
print(f"(matA)^3: \n{matrix_power(A, 3)}")

(matA)^3: 
[[ 447. 1263. 1256.]
 [ 532. 1577. 1544.]
 [ 432. 1305. 1288.]]


## Regular Markov Chain as a Matrix

### Creating Stochastic Matrices

In [7]:
def create_stochastic_matrix(size):
    mat = np.zeros((size, size))
    for i in range(size):
        row_sum = 0
        for j in range(size - 1):
            mat[i][j] = np.random.uniform(0, (1 - row_sum))
            row_sum += mat[i][j]
        mat[i][-1] = 1 - row_sum
    return mat

### Checking Regular Matrix

In [8]:
def check_regular_matrix(matA, iterations= 1000):
    for i in range (1, iterations + 1):
        mat = matrix_power(matA, i)
        if (type(mat) == int): return -1 # matrix_power() returns -1 if error
        mat_size = len(mat) # Matrix has to be a square
        count = 0
        for j in range(mat_size):
            for k in range(mat_size):
                if (mat[j][k] == 0): 
                    break
                else: 
                    count += 1
        if (count == (mat_size ** 2)): 
            print(f"The matrix is regular, and when it is raised to power {i}, it is positive.")
            break
        else:
            print(f"The matrix is not regular upto its {i}th power", end = '\r')
    return

### Implementation

In [9]:
# Debugging for validity of stochastic matrix
# Generate two random stochastic matrices
for i in range(2):
    b = create_stochastic_matrix(4)
    for i in range(4):
        for j in range(4):
            if (b[i][j] < 0 or b[i][j] > 1):
                print("Not Valid Stochastic Matrix")    
    print(b)
    print()

[[0.73082699 0.06051967 0.00462475 0.20402859]
 [0.1834301  0.64209439 0.09913493 0.07534058]
 [0.51829029 0.32303717 0.01298726 0.14568528]
 [0.86844434 0.08930769 0.04013199 0.00211598]]

[[3.74944344e-01 8.10185631e-02 1.32642174e-01 4.11394918e-01]
 [6.19246282e-01 2.43981220e-01 1.24087091e-02 1.24363789e-01]
 [7.46814017e-01 2.39696178e-01 1.30688724e-02 4.20932857e-04]
 [8.97853441e-01 2.93998916e-02 1.57511660e-02 5.69955015e-02]]



In [10]:
check_regular_matrix(b)
D = np.array([[0.12351425, 0.50276079, 0.10840787, 0.26531709],
                 [0.8681274, 0., 0.11212622, 0.01974638],
                 [0.55888506, 0.14277434, 0.15657036, 0.14177024],
                 [0.11016633, 0.07586725, 0.40404501, 0.40992142]])
print(f'MatD: \n{D}')
check_regular_matrix(D)
E = np.array([0, 0.5, 0.5, 9.5, 0, 0.5, 0, 1, 0]).reshape(3, -1)
print(f'MatE: \n{E}')
check_regular_matrix(E)

The matrix is regular, and when it is raised to power 1, it is positive.
MatD: 
[[0.12351425 0.50276079 0.10840787 0.26531709]
 [0.8681274  0.         0.11212622 0.01974638]
 [0.55888506 0.14277434 0.15657036 0.14177024]
 [0.11016633 0.07586725 0.40404501 0.40992142]]
The matrix is regular, and when it is raised to power 2, it is positive.
MatE: 
[[0.  0.5 0.5]
 [9.5 0.  0.5]
 [0.  1.  0. ]]
The matrix is regular, and when it is raised to power 4, it is positive.


In [11]:
F = np.array([[0.7, 0, 0.3], 
              [0, 1, 0], 
              [0.2, 0, 0.8]]).reshape(3, -1)
print(f"MatF: \n{F}")
check_regular_matrix(F, 1000)

MatF: 
[[0.7 0.  0.3]
 [0.  1.  0. ]
 [0.2 0.  0.8]]


## Null Space of a Matrix
The null space of a matrix A is the same as the null space for its row reduced echelon form (rref(A)).

In [12]:
def rref(matA):
    rref = matA.copy()
    pivot = 0
    rows = len(rref)
    cols = len(rref[0])
    rank = 0
    for r in range(rows):
        if (cols < pivot):
            break
        i = r
        while (rref[i, pivot] == 0):
            i += 1
            if (rows == 1):
                i = r
                pivot += 1
                if (cols == pivot):
                    break
        vec = rref[i]
        rref[i] = rref[r]
        rref[r] = vec
        if (rref[r][pivot] != 0):
            rref[r] = rref[r] / rref[r][pivot]
        for i in range(rows):
            if (i != r):
                rref[i] -= (rref[r]*rref[i][pivot]) 
        pivot += 1
    for row in range(rows):
        for col in range(cols):
            if (rref[row][col] != 0):
                rank += 1
                break
                
    return rref, rank

In [13]:
G = np.array([1, 2, -1, -4, 2, 3, -1, -11, -2, 0, -3, 22]).reshape(3, -1)
print(f'matG: \n{G}')
rref_g, r = rref(G)
print(f"rref(G): \n{rref_g}")
G = sp.Matrix(G)
print (f"sympy.G.rref(): \n{np.array(G.rref()[0])}")

matG: 
[[  1   2  -1  -4]
 [  2   3  -1 -11]
 [ -2   0  -3  22]]
rref(G): 
[[ 1  0  0 -8]
 [ 0  1  0  1]
 [ 0  0  1 -2]]
sympy.G.rref(): 
[[1 0 0 -8]
 [0 1 0 1]
 [0 0 1 -2]]


In [14]:
H = np.array([[1, 0, 1, 3], 
              [2, 3, 4, 7], 
              [-1, -3, -3, -4]]).reshape(3, -1)
print(f"matH:\n{H}")
dimension = len(H[0])
print(f"Dimension(matH): {dimension}")
H = sp.Matrix(H)
rank_H = H.rank()
print(f"Rank(matH): {rank_H}")
null_space = [np.array(mat) for mat in H.nullspace()]
print("H.nullspace(): ")
[print(f'vector_{i+1}:\n{null_space[i]}') for i in range(len(null_space))]
print(f"Rank ({H.rank()}) + Nullity ({len(null_space)}) = Dimension ({dimension})")

matH:
[[ 1  0  1  3]
 [ 2  3  4  7]
 [-1 -3 -3 -4]]
Dimension(matH): 4
Rank(matH): 2
H.nullspace(): 
vector_1:
[[-1]
 [-2/3]
 [1]
 [0]]
vector_2:
[[-3]
 [-1/3]
 [0]
 [1]]
Rank (2) + Nullity (2) = Dimension (4)
